<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>HumanoidRetargeter.Dev</AssemblyName>
    <RootNamespace>HumanoidRetargeter</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Code\HumanoidRetargeter\**\*.cs" />
  </ItemGroup>

</Project>
